[project]
name = "comsol_module"
version = "0.2.0"
description = "Module to read and process output vtus/txt files from COMSOL."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas>=3.0.5",
    "pyvista>=0.44.2",
]

[project.optional-dependencies]
jupyter = [
    "trame-jupyter-extension>=2.1.4",
    "ipykernel>=6.29.5",
    "nbformat>=5.10.4",
    "jupyterlab>=4.4.0",
]

[tool.uv]
default-groups = []

[dependency-groups]
dev = [
    {include-group = 'test'},
    {include-group = 'docs'},
]

test = [
    'Ruff         >= 0.11',
    'basedPyright >= 1.29',
    'pyTest       >= 8',
    "pytest-cov>=7",
    'codecov      >= 2',
]

docs = [
    'Sphinx      >= 8',
    'MyST-parser >= 1',
    'Furo        >= 2024',
]

[tool.pytest.ini_options]
pythonpath = "src"
